### ISSUE TITLE
TypeError: Object type <class 'str'> cannot be passed to C code

### ISSUE THREAD

**Issue by davidtys** [berlincode/sjcl#7]
Hello,
In python 3.6, when I run your example I have this error

```
>>> from sjcl import SJCL
>>> cyphertext = SJCL().encrypt("secret message to encrypt", "shared_secret")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/lib/python3.6/site-packages/sjcl/sjcl.py", line 180, in encrypt
    ciphertext = cipher.encrypt(plaintext)
  File "/path/lib/python3.6/site-packages/Crypto/Cipher/_mode_ccm.py", line 366, in encrypt
    self._update(plaintext)
  File "/path/lib/python3.6/site-packages/Crypto/Cipher/_mode_ccm.py", line 298, in _update
    self._t = self._mac.encrypt(assoc_data_pt[:update_len])[-16:]
  File "/path/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 162, in encrypt
    c_uint8_ptr(plaintext),
  File "/path/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 196, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
```

Thank you.

**Comment by berlincode** [comment]
Sorry for the late response. Had to install python3.6 first.

You need to supply a bytes object as first parameter to encrypt(). Just prefix your secret message with a 'b':

cyphertext = SJCL().encrypt(b"secret message to encrypt", "shared_secret")

**Comment by berlincode** [comment]
Updated the Readme.md accordingly.
